language: python

python:
  - "pypy"
  - "3.8"

install:
  - pip install coveralls
  - pip install coverage
  - pip install nose

script:
  - python setup.py install
  - python setup.py nosetests --with-coverage

after_success:
  - coveralls
